### ISSUE TITLE
GET request cannot parse params

### ISSUE THREAD

**Issue by orest-kostiuk** [andriy-baran/rspec_request_helpers#7]
GET request cannot parse params

**Comment by andriy-baran** [comment]
@Ckazo4nik Please set headers like this
```ruby
headers do
  {
    'Content-Type' => 'application/json',
    'Accept' => 'application/json'
  }
end
```

**Comment by andriy-baran** [comment]
@orest-kostiuk You are right. Thanks for your help

**Comment by orest-kostiuk** [comment]
> @orest-kostiuk You are right. Thanks for your help

Great. Always happy to help! :)
